#!/bin/bash

# -d: run the container in detached mode(in the background)
# -p 80:80: map port 80 of the host to port 80 in the container
# --restart always: Always restart the container if it stops. If it is manually stopped, it is restarted only when Docker daemon restarts or the container itself is manually restarted

docker run -d -p 5000:80 --name overlord --restart always --network selvi-net nginx