#!/bin/bash

# docker run -it --rm debian
# The build-essentials packages are meta-packages that are necessary for compiling software.

apt-get update
apt-get upgrade
apt install git
apt install build-essential # for gcc

# apt install nano
# #include <stdio.h>
# int main(){ printf("test!\n"); return (0); }