#!/bin/bash

# docker volume create	Create a volume
# docker volume inspect	Display detailed information on one or more volumes
# docker volume ls	List volumes
# docker volume prune	Remove all unused local volumes
# docker volume rm	Remove one or more volumes

docker volume ls