#!/bin/bash

# https://flask.palletsprojects.com/en/2.1.x/quickstart/
# installs a container
docker run -dit --name Abathur -p 3000:3000 -v /home/selvi/docker-py:/root python:2-slim

docker exec Abathur pip install Flask

# create a file called app.py
echo -e 'from flask import Flask\napp = Flask(__name__)\n@app.route("/")\ndef hello_world():\n\treturn"<h1>Hello World</h1>"' > /home/selvi/docker-py/app.py

# 1st we need to tell the app to work by setting FLASK_APP env. variable to our app.
# flask run - runs the application on a local development server.
# set port to 3000. set host to '0.0.0.0' to have the server available externally as well. Defaults to '127.0.0.1' (Local host).

docker exec -e FLASK_APP=/root/app.py Abathur flask run --host=0.0.0.0 --port 3000

# open localhost:3000 to check if it's running.